on:
  push:
    branches:
      - master

name: Testing
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.0.2"
          cabal-version: "3.4.0.0"

      - name: Running tests
        run: cabal test
