on: [push]
name: build
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: "latest"
          cabal-version: "latest"
      - run: cabal test
