on: [push]
name: build
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.0.2"
          cabal-version: "3.4.0.0"
      - run: cabal test
